name: client

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Clear NPM Cache
      run: npm cache clean --force

    - name: Install npm dependencies
      run: npm install --legacy-peer-deps

    - name: Run Build
      env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        VITE_KEY_ID: ${{ secrets.VITE_KEY_ID }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.VITE_APP_ID }} 
        VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }} 
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "client/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: "/home/ubuntu/client"
        EXCLUDE: "/node_modules/, /.git/"

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/client
          npm install --production
          pm2 restart next-app || pm2 start npm --name "next-app" -- start